version: '3.1'
# Set network
networks:
  frontend:
    ipam:
      config:
        - subnet: ${SUBNET_IP}  
# SERVICES
services:
# ------ Configure DB -------
  mysql:
    image: localhost:5000/petclinic-db:${TAG}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
 #    - MYSQL_ALLOW_EMPTY_PASSWORD=true
 #    - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
 #    - MYSQL_DATABASE=${DB_NAME}
    volumes:
       - /backupDB:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:    
          frontend:
             ipv4_address: ${IP_DB}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
#  ----------- Configure APP ----------  
  appspring:
    image: localhost:5000/petclinic-app:${TAG}
    ports:
      - "8080:8080"
    networks:
            frontend:
                ipv4_address: ${IP_APP}
    environment:
        - DB_HOST=${IP_DB} 
        - DB_PORT=${DB_PORT} 
        - DB_NAME=${MYSQL_DATABASE}
        - DB_USER=${MYSQL_USER} 
        - DB_PASS=${DB_PASS} 
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
 
