version: "3.3"
services:
 registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  networks:
      vpcbr:
        ipv4_address: 10.5.0.6  
  volumes:
    - /registry_doceker:/var/lib/registry
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
        
